# Generated by Django 3.2.12 on 2022-03-05 23:44

import LemurApp.models.inmate
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250, unique=True)),
                ('handle', models.IntegerField(unique=True, verbose_name='Handle (leave this as 1!)')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('restrictsHardbacks', models.BooleanField(default=False, verbose_name='This facility restricts hardbacks')),
                ('otherRestrictions', models.CharField(blank=True, default='', max_length=250, verbose_name='Other Restrictions')),
                ('address', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmate_id', LemurApp.models.inmate.InmateIDField(max_length=250, null=True, unique=True, verbose_name='Inmate ID')),
                ('inmate_doc_id', models.CharField(blank=True, default='', max_length=250, verbose_name='Inmate DOC ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last name')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LemurApp.facility')),
            ],
        ),
        migrations.CreateModel(
            name='LemurSettingsStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingName', models.CharField(max_length=250, unique=True)),
                ('settingValue', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Lemur Settings',
                'ordering': ['settingName'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('OPEN', 'Open'), ('RETURNED', 'Returned')], default='OPEN', max_length=20, verbose_name='Order status')),
                ('date_opened', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Date opened')),
                ('date_closed', models.DateTimeField(blank=True, null=True, verbose_name='Date closed')),
                ('sender', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sender')),
                ('notes', models.CharField(blank=True, default='', max_length=2048, verbose_name='Notes')),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='LemurApp.inmate', verbose_name='Inmate')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=250, verbose_name='Author')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Creation date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='LemurApp.order')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
